name       : kpipewire
version    : 5.26.4
release    : 2
source     :
    - https://cdn.download.kde.org/stable/plasma/5.26.4/kpipewire-5.26.4.tar.xz : 46274e57d863fabe5e344c0e29f48d1eb27cc7318c923d33056d025870a5f634
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Components relating to pipewire use in Plasma
description: |
    Components relating to pipewire use in Plasma
patterns   :
    - /usr/lib64/libKPipeWire*.so
    - /usr/lib64/libKPipeWireRecord*.so
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(gbm)
    - pkgconfig(libavformat)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kwayland-devel
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
