name       : kpipewire
version    : 5.26.3
release    : 1
source     :
    - https://cdn.download.kde.org/stable/plasma/5.26.3/kpipewire-5.26.3.tar.xz : b4a865a38c8e2b281df4fe1405880fae4ed1ecba3229454b8af8a34dbecd7ca4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Components relating to pipewire use in Plasma
description: |
    Components relating to pipewire use in Plasma
patterns   :
    - /usr/lib64/libKPipeWire*.so
    - /usr/lib64/libKPipeWireRecord*.so
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(gbm)
    - pkgconfig(libavformat)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kwayland-devel
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
